name: Deploy to Firebase Hosting and Functions

on:
  push:
    branches:
      - main
      - dev

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # Changed to Node 18 for Firebase Functions compatibility
          cache: 'npm'
      
      # Install frontend dependencies
      - name: Install frontend dependencies
        run: npm ci
      
      # Install functions dependencies
      - name: Install functions dependencies
        run: |
          cd functions
          npm ci
      
      # Build functions (TypeScript compilation)
      - name: Build functions
        run: |
          cd functions
          npm run build
      
      - name: Set Development Environment
        if: github.ref == 'refs/heads/dev'
        run: |
          echo "VITE_ENV=development" >> $GITHUB_ENV
          echo "Building for development environment"
      
      - name: Set Production Environment
        if: github.ref == 'refs/heads/main'
        run: |
          echo "VITE_ENV=production" >> $GITHUB_ENV
          echo "Building for production environment"
      
      # Build frontend
      - name: Build frontend
        run: npm run build
      
      - name: Deploy to Production (Live Channel)
        if: github.ref == 'refs/heads/main'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_LAVAFAST_LAUNDRY_SERVICE }}'
          channelId: live
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
      
      - name: Deploy to Dev Channel
        if: github.ref == 'refs/heads/dev'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_LAVAFAST_LAUNDRY_SERVICE }}'
          channelId: dev
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
          expires: 7d
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks